config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("readitapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

readitapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save


# Create your models here.

class User(AbstractUser):
    avatar = models.ImageField(upload_to='user/', blank=True, null=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.username


class Category(models.Model):
    cat_name = models.CharField(max_length=100)

    def __str__(self):
        return self.cat_name


class Tag(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag


class BlogModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/')
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tag = models.ManyToManyField(Tag)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title[:30]

    def get_absolute_url(self):
        return reverse('blog_single', kwargs={'pk': str(self.pk)})


class ContactModel(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    create = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('contact')

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(BlogModel, on_delete=models.CASCADE)
    message = models.TextField()
    parent = models.ForeignKey('self', null=True, blank=True,on_delete=models.CASCADE,related_name='replies')
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.user.username}:{self.message[:30]} >> {self.parent}'

    @property
    def children(self):
        return Message.objects.filter(parent=self).reverse()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/about.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end"
                     style="background-image:url({% static 'images/about.jpg' %});">
                    <a href="https://vimeo.com/45830194"
                       class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
            </div>
            <div class="col-md-6 pl-md-5 py-md-5">
                <div class="row justify-content-start pt-3 pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <span class="subheading">Welcome to Readit</span>
                        <h2 class="mb-4">We give you the best articles you want.</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <div class="tabulation-2 mt-4">
                            <ul class="nav nav-pills nav-fill d-md-flex d-block">
                                <li class="nav-item mb-md-0 mb-2">
                                    <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
                                </li>
                                <li class="nav-item px-lg-2 mb-md-0 mb-2">
                                    <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
                                </li>
                            </ul>
                            <div class="tab-content bg-light rounded mt-2">
                                <div class="tab-pane container p-0 active" id="home1">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home2">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home3">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section testimony-section">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
                <span class="subheading">Testimonial</span>
                <h2 class="mb-4">Happy Clients</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel ftco-owl">
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia
                                    and Consonantia, there live the blind texts.</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({% static 'images/person_1.jpg' %})"></div>
                                    <div class="pl-3">
                                        <p class="name">Roger Scott</p>
                                        <span class="position">Marketing Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia
                                    and Consonantia, there live the blind texts.</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({% static 'images/person_2.jpg' %})"></div>
                                    <div class="pl-3">
                                        <p class="name">Roger Scott</p>
                                        <span class="position">Marketing Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia
                                    and Consonantia, there live the blind texts.</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({% static 'images/person_3.jpg' %})"></div>
                                    <div class="pl-3">
                                        <p class="name">Roger Scott</p>
                                        <span class="position">Marketing Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia
                                    and Consonantia, there live the blind texts.</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({% static 'images/person_1.jpg' %})"></div>
                                    <div class="pl-3">
                                        <p class="name">Roger Scott</p>
                                        <span class="position">Marketing Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="testimony-wrap py-4">
                            <div class="text">
                                <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia
                                    and Consonantia, there live the blind texts.</p>
                                <div class="d-flex align-items-center">
                                    <div class="user-img" style="background-image: url({% static 'images/person_2.jpg' %})"></div>
                                    <div class="pl-3">
                                        <p class="name">Roger Scott</p>
                                        <span class="position">Marketing Manager</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
44
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Blog Single</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'blog' %}">Blog <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{ blog.image.url }}" alt class="img-fluid">
                </p>
                <h2 class="mb-3">{{ blog.title }}</h2>
                <p>{{ blog.content }}</p>

                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for t in blog.tag.all  %}
                        <a href="{% url 'blog' %}?search={{ t }}#" class="tag-cloud-link">{{ t }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{{ blog.user.avatar.url }}" alt="Image placeholder" class="img-fluid mb-4" style="height: 243.31px; width: 203.41px;">
                    </div>
                    <div class="desc">
                        <h3>{{ blog.user.username }}</h3>
                        <p>{{ blog.user.bio }}</p>
                    </div>
                </div>
                <div class="pt-5 mt-5">
                    <h3 class="mb-5">{{ blog.message_set.count }} Comments</h3>
                    <ul class="comment-list">
                        <li class="comment">

                             {% for i in message %}
                                 {% if i.is_parent %}
                            <div class="vcard bio">
                                <img src="{{ i.user.avatar.url }}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                                <h3>{{ i.user.username }}</h3>
                                <div class="meta mb-3">{{ i.created|date:'F d Y' }} at {{ i.created|date:'h : m'}}</div>
                                <p>{{ i.message }}</p>
                                <form action="" method="POST" id="main_form" class="comment_form">
                                    <div>
                                        <input class="form-control" style="width: 55%" type="text" name="message"> <input
                                            type="hidden" value="{{ i.pk }}" name="parent"> {% csrf_token %}</div>
                                </form>
                            </div>
                                 {% endif %}
                            {% for j in i.children %}
                            <ul class="children">
                                <li class="comment">
                                    <div class="vcard bio">
                                        <img src="{{ j.user.avatar.url }}" alt="Image placeholder">
                                    </div>
                                    <div class="comment-body">
                                        <p>{{ j.user.username }} <b>to</b> {{ i.user.username }} <b>message</b> {{ i.message }}</p>
                                        <div class="meta mb-3">{{ i.created|date:'F d Y' }} at {{ i.created|date:'h : m'}}</div>
                                        <p>{{ j.message }}</p>
                                        <form action="" method="POST" id="main_form" class="comment_form">
                                            <div>
                                                <input class="form-control" style="width: 55%" type="text" name="message">
                                                <input type="hidden" value="{{ j.id }}" name="parent"> {% csrf_token %}
                                            </div>
                                        </form>
                                    </div>

                                </li>
                            </ul>

                            {% endfor %}
                            {% endfor %}

                        </li>
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form action="#" method="post" class="p-5 bg-light">
                            {% csrf_token %}

                            <div class="form-group">
                               {{ form.message }}
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">


                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>

                        {% for c in cat %}
                        <li><a href="{% url 'blog' %}?search={{ c }}#">{{ c }}<span class="ion-ios-arrow-forward"></span></a></li>
                        {% endfor %}

                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    {% for bl in resblog %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ bl.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{{ bl.get_absolute_url }}">{{ bl.title }}</a></h3>
                            <div class="meta">
                                <div><a href="{{ bl.get_absolute_url }}"><span class="icon-calendar"></span>{{ bl.created|date:'M. d, Y' }}</a></div>
                                <div><a href="{{ bl.get_absolute_url }}"><span class="icon-person"></span>{{ bl.user }}</a></div>
                                <div><a href="{{ bl.get_absolute_url }}"><span class="icon-chat"></span>{{ bl.message_set.count }}</a></div>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">

                        {% for tg in tag %}
                        <a href="{% url 'blog' %}?search={{ tg }}#" class="tag-cloud-link">{{ tg }}</a>
                       {% endfor %}

                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome to</h2>
                <h1 class="mb-4 mb-md-0">Readit blog</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="text">
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                            <div class="mouse">
                                <a href="#" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section bg-light" id="mytab" role="tablist">
    <div class="container">
        <div class="row d-flex">

                <div class="sidebar-box">
                    <form action="#" class="search-form" >
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter" name="search">
                        </div>
                    </form>
                </div>

            {% for b in blog %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <a href="{{ b.get_absolute_url }}" class="block-20" style="background-image: url('{{ b.image.url }}');">
                    </a>
                    <div class="text p-4 float-right d-block">
                        <div class="topper d-flex align-items-center">
                            <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                <span class="day">{{ b.created|date:'d'}}</span>
                            </div>
                            <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                <span class="yr">{{ b.created|date:'Y' }}</span>
                                <span class="mos">{{ b.created|date:'F' }}</span>
                            </div>
                        </div>
                        <h3 class="heading mb-3"><a href="{{ b.get_absolute_url }}">{{ b.title }}</a></h3>
                        <p>{{ b.content }}</p>
                        <p><a href="{{ b.get_absolute_url }}" class="btn-custom"><span class="ion-ios-arrow-round-forward mr-3"></span>Read
                            more</a></p>
                    </div>
                </div>
            </div>
         {% endfor %}

        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">

                    <ul>
                     {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ page_obj.previous_page_number }}#mytab"><</a>
                                </li>

                                 <li>
                                    <a href="?page={{ page_obj.previous_page_number }}#mytab">{{ page_obj.previous_page_number }}</a>
                                </li>

                     {% endif %}

                                <li class="page-item active">
                                    <a href="?page={{ page_obj.number }}#mytab">{{ page_obj.number }}</a>
                                </li>

                    {% if page_obj.has_next %}

                                <li >
                                    <a href="?page={{ page_obj.next_page_number }}#mytab">{{ page_obj.next_page_number }}</a>
                                </li>

                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}#mytab">></a>
                                </li>
                    {% endif %}
                    </ul>

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Contact us</h1>
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="{% url 'home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span>
                    <span class="mr-2"><a href="{% url 'about' %}">About <i class="ion-ios-arrow-forward"></i></a></span>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section contact-section">
    <div class="container">
        <div class="row d-flex mb-5 contact-info">
            <div class="col-md-12 mb-4">
                <h2 class="h3">Contact Information</h2>
            </div>
            <div class="w-100"></div>
            <div class="col-md-3">
                <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
            </div>
            <div class="col-md-3">
                <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
            </div>
            <div class="col-md-3">
                <p><span>Email:</span> <a
                        href="https://preview.colorlib.com/cdn-cgi/l/email-protection#abc2c5cdc4ebd2c4ded9d8c2dfce85c8c4c6"><span
                        class="__cf_email__"
                        data-cfemail="771e191118370e180205041e03125914181a">[email&#160;protected]</span></a></p>
            </div>
            <div class="col-md-3">
                <p><span>Website</span> <a href="#">yoursite.com</a></p>
            </div>
        </div>
        <div class="row block-9 no-gutters">
            <div class="col-lg-6 order-md-last d-flex">
                <form action="#" class="bg-light p-4 p-md-5 contact-form" method="post">

                    {% csrf_token %}

                    <div class="form-group">
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        {{ form.email }}
                    </div>

                    <div class="form-group">
                        {{ form.subject }}
                    </div>

                    <div class="form-group">
                        {{ form.message }}
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                    </div>
                </form>
            </div>
            <div class="col-lg-6 d-flex">
                <div id="map" class="bg-white"></div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome</h2>
                <h1 class="mb-4 mb-md-0">Login</h1>
                <div class="row">
                    <div class="col-md-7">
                                <a href="#" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
            <div class="col-lg-8 ftco-animate">
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Login</h3>
                        <form action="#" class="p-5 bg-light" method="post">
                            {% csrf_token %}

                            {{ message }}

                            {{ form.errors }}

                            <div class="form-group">
                                {{ form.username }}
                            </div>

                            <div class="form-group">
                               {{ form.password }}
                            </div>

                            <a href="{% url 'register' %}" class="nav-link"><h4>Register now!</h4></a>


                            <div class="form-group">
                                <input type="submit" value="Login" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
            </div>
{% endblock %}